// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.3
// source: api/v1/weibo.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewOriginWeiboReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Size int32  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *NewOriginWeiboReq) Reset() {
	*x = NewOriginWeiboReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_weibo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewOriginWeiboReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewOriginWeiboReq) ProtoMessage() {}

func (x *NewOriginWeiboReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_weibo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewOriginWeiboReq.ProtoReflect.Descriptor instead.
func (*NewOriginWeiboReq) Descriptor() ([]byte, []int) {
	return file_api_v1_weibo_proto_rawDescGZIP(), []int{0}
}

func (x *NewOriginWeiboReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *NewOriginWeiboReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type NewOriginWeiboReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response map[string][]byte `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *NewOriginWeiboReply) Reset() {
	*x = NewOriginWeiboReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_weibo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewOriginWeiboReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewOriginWeiboReply) ProtoMessage() {}

func (x *NewOriginWeiboReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_weibo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewOriginWeiboReply.ProtoReflect.Descriptor instead.
func (*NewOriginWeiboReply) Descriptor() ([]byte, []int) {
	return file_api_v1_weibo_proto_rawDescGZIP(), []int{1}
}

func (x *NewOriginWeiboReply) GetResponse() map[string][]byte {
	if x != nil {
		return x.Response
	}
	return nil
}

type NewAllWeiboReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *NewAllWeiboReq) Reset() {
	*x = NewAllWeiboReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_weibo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewAllWeiboReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAllWeiboReq) ProtoMessage() {}

func (x *NewAllWeiboReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_weibo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAllWeiboReq.ProtoReflect.Descriptor instead.
func (*NewAllWeiboReq) Descriptor() ([]byte, []int) {
	return file_api_v1_weibo_proto_rawDescGZIP(), []int{2}
}

func (x *NewAllWeiboReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type NewAllWeiboReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response map[string][]byte `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *NewAllWeiboReply) Reset() {
	*x = NewAllWeiboReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_weibo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewAllWeiboReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAllWeiboReply) ProtoMessage() {}

func (x *NewAllWeiboReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_weibo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAllWeiboReply.ProtoReflect.Descriptor instead.
func (*NewAllWeiboReply) Descriptor() ([]byte, []int) {
	return file_api_v1_weibo_proto_rawDescGZIP(), []int{3}
}

func (x *NewAllWeiboReply) GetResponse() map[string][]byte {
	if x != nil {
		return x.Response
	}
	return nil
}

type HelloReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *HelloReq) Reset() {
	*x = HelloReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_weibo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReq) ProtoMessage() {}

func (x *HelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_weibo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReq.ProtoReflect.Descriptor instead.
func (*HelloReq) Descriptor() ([]byte, []int) {
	return file_api_v1_weibo_proto_rawDescGZIP(), []int{4}
}

func (x *HelloReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type HelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_weibo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_weibo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_api_v1_weibo_proto_rawDescGZIP(), []int{5}
}

func (x *HelloReply) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type NewAddWeiboReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Desc string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *NewAddWeiboReq) Reset() {
	*x = NewAddWeiboReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_weibo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewAddWeiboReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAddWeiboReq) ProtoMessage() {}

func (x *NewAddWeiboReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_weibo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAddWeiboReq.ProtoReflect.Descriptor instead.
func (*NewAddWeiboReq) Descriptor() ([]byte, []int) {
	return file_api_v1_weibo_proto_rawDescGZIP(), []int{6}
}

func (x *NewAddWeiboReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *NewAddWeiboReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NewAddWeiboReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type NewAddWeiboReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewAddWeiboReply) Reset() {
	*x = NewAddWeiboReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_weibo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewAddWeiboReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAddWeiboReply) ProtoMessage() {}

func (x *NewAddWeiboReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_weibo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAddWeiboReply.ProtoReflect.Descriptor instead.
func (*NewAddWeiboReply) Descriptor() ([]byte, []int) {
	return file_api_v1_weibo_proto_rawDescGZIP(), []int{7}
}

type WeiboUsersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size int32  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Uid  string `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *WeiboUsersReq) Reset() {
	*x = WeiboUsersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_weibo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeiboUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeiboUsersReq) ProtoMessage() {}

func (x *WeiboUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_weibo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeiboUsersReq.ProtoReflect.Descriptor instead.
func (*WeiboUsersReq) Descriptor() ([]byte, []int) {
	return file_api_v1_weibo_proto_rawDescGZIP(), []int{8}
}

func (x *WeiboUsersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *WeiboUsersReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *WeiboUsersReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type WeiboUsersReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*WeiboUsersReply_One `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *WeiboUsersReply) Reset() {
	*x = WeiboUsersReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_weibo_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeiboUsersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeiboUsersReply) ProtoMessage() {}

func (x *WeiboUsersReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_weibo_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeiboUsersReply.ProtoReflect.Descriptor instead.
func (*WeiboUsersReply) Descriptor() ([]byte, []int) {
	return file_api_v1_weibo_proto_rawDescGZIP(), []int{9}
}

func (x *WeiboUsersReply) GetList() []*WeiboUsersReply_One {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *WeiboUsersReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type WeiboUsersReply_One struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UrlPc  string `protobuf:"bytes,2,opt,name=url_pc,json=urlPc,proto3" json:"url_pc,omitempty"`
	UrlWeb string `protobuf:"bytes,3,opt,name=url_web,json=urlWeb,proto3" json:"url_web,omitempty"`
	Desc   string `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *WeiboUsersReply_One) Reset() {
	*x = WeiboUsersReply_One{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_weibo_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeiboUsersReply_One) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeiboUsersReply_One) ProtoMessage() {}

func (x *WeiboUsersReply_One) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_weibo_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeiboUsersReply_One.ProtoReflect.Descriptor instead.
func (*WeiboUsersReply_One) Descriptor() ([]byte, []int) {
	return file_api_v1_weibo_proto_rawDescGZIP(), []int{9, 0}
}

func (x *WeiboUsersReply_One) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *WeiboUsersReply_One) GetUrlPc() string {
	if x != nil {
		return x.UrlPc
	}
	return ""
}

func (x *WeiboUsersReply_One) GetUrlWeb() string {
	if x != nil {
		return x.UrlWeb
	}
	return ""
}

func (x *WeiboUsersReply_One) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

var File_api_v1_weibo_proto protoreflect.FileDescriptor

var file_api_v1_weibo_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x65, 0x69, 0x62, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x73, 0x73, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x22,
	0x39, 0x0a, 0x11, 0x4e, 0x65, 0x77, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x57, 0x65, 0x69, 0x62,
	0x6f, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x9c, 0x01, 0x0a, 0x13, 0x4e,
	0x65, 0x77, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x48, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x72, 0x73, 0x73, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31,
	0x2e, 0x4e, 0x65, 0x77, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x3b, 0x0a, 0x0d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x22, 0x0a, 0x0e, 0x4e, 0x65, 0x77,
	0x41, 0x6c, 0x6c, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x96, 0x01,
	0x0a, 0x10, 0x4e, 0x65, 0x77, 0x41, 0x6c, 0x6c, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x45, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x72, 0x73, 0x73, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31,
	0x2e, 0x4e, 0x65, 0x77, 0x41, 0x6c, 0x6c, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x3b, 0x0a, 0x0d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x1e, 0x0a, 0x08, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x20, 0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x48, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x41,
	0x64, 0x64, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65,
	0x73, 0x63, 0x22, 0x12, 0x0a, 0x10, 0x4e, 0x65, 0x77, 0x41, 0x64, 0x64, 0x57, 0x65, 0x69, 0x62,
	0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x49, 0x0a, 0x0d, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x22, 0xb8, 0x01, 0x0a, 0x0f, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x32, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x72, 0x73, 0x73, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e,
	0x57, 0x65, 0x69, 0x62, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e,
	0x4f, 0x6e, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x1a,
	0x5b, 0x0a, 0x03, 0x4f, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x75, 0x72, 0x6c, 0x5f,
	0x70, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x75, 0x72, 0x6c, 0x50, 0x63, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x72, 0x6c, 0x5f, 0x77, 0x65, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x72, 0x6c, 0x57, 0x65, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x32, 0xe0, 0x02, 0x0a,
	0x05, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x12, 0x33, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12,
	0x13, 0x2e, 0x72, 0x73, 0x73, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x72, 0x73, 0x73, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4e, 0x0a, 0x0e, 0x4e,
	0x65, 0x77, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x12, 0x1c, 0x2e,
	0x72, 0x73, 0x73, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x4f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x72, 0x73,
	0x73, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x4f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x47, 0x0a, 0x0b, 0x4e,
	0x65, 0x77, 0x41, 0x6c, 0x6c, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x12, 0x19, 0x2e, 0x72, 0x73, 0x73,
	0x68, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x41, 0x6c, 0x6c, 0x57, 0x65, 0x69,
	0x62, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x72, 0x73, 0x73, 0x68, 0x75, 0x62, 0x2e, 0x76,
	0x31, 0x2e, 0x4e, 0x65, 0x77, 0x41, 0x6c, 0x6c, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x30, 0x01, 0x12, 0x45, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x41, 0x64, 0x64, 0x57, 0x65,
	0x69, 0x62, 0x6f, 0x12, 0x19, 0x2e, 0x72, 0x73, 0x73, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e,
	0x4e, 0x65, 0x77, 0x41, 0x64, 0x64, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x1b,
	0x2e, 0x72, 0x73, 0x73, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x41, 0x64,
	0x64, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x42, 0x0a, 0x0a, 0x57,
	0x65, 0x69, 0x62, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x18, 0x2e, 0x72, 0x73, 0x73, 0x68,
	0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x65, 0x69, 0x62, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x72, 0x73, 0x73, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e,
	0x57, 0x65, 0x69, 0x62, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42,
	0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x58, 0x69,
	0x65, 0x57, 0x65, 0x69, 0x58, 0x69, 0x65, 0x2f, 0x72, 0x73, 0x73, 0x68, 0x75, 0x62, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_weibo_proto_rawDescOnce sync.Once
	file_api_v1_weibo_proto_rawDescData = file_api_v1_weibo_proto_rawDesc
)

func file_api_v1_weibo_proto_rawDescGZIP() []byte {
	file_api_v1_weibo_proto_rawDescOnce.Do(func() {
		file_api_v1_weibo_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_weibo_proto_rawDescData)
	})
	return file_api_v1_weibo_proto_rawDescData
}

var file_api_v1_weibo_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_v1_weibo_proto_goTypes = []interface{}{
	(*NewOriginWeiboReq)(nil),   // 0: rsshub.v1.NewOriginWeiboReq
	(*NewOriginWeiboReply)(nil), // 1: rsshub.v1.NewOriginWeiboReply
	(*NewAllWeiboReq)(nil),      // 2: rsshub.v1.NewAllWeiboReq
	(*NewAllWeiboReply)(nil),    // 3: rsshub.v1.NewAllWeiboReply
	(*HelloReq)(nil),            // 4: rsshub.v1.HelloReq
	(*HelloReply)(nil),          // 5: rsshub.v1.HelloReply
	(*NewAddWeiboReq)(nil),      // 6: rsshub.v1.NewAddWeiboReq
	(*NewAddWeiboReply)(nil),    // 7: rsshub.v1.NewAddWeiboReply
	(*WeiboUsersReq)(nil),       // 8: rsshub.v1.WeiboUsersReq
	(*WeiboUsersReply)(nil),     // 9: rsshub.v1.WeiboUsersReply
	nil,                         // 10: rsshub.v1.NewOriginWeiboReply.ResponseEntry
	nil,                         // 11: rsshub.v1.NewAllWeiboReply.ResponseEntry
	(*WeiboUsersReply_One)(nil), // 12: rsshub.v1.WeiboUsersReply.One
}
var file_api_v1_weibo_proto_depIdxs = []int32{
	10, // 0: rsshub.v1.NewOriginWeiboReply.response:type_name -> rsshub.v1.NewOriginWeiboReply.ResponseEntry
	11, // 1: rsshub.v1.NewAllWeiboReply.response:type_name -> rsshub.v1.NewAllWeiboReply.ResponseEntry
	12, // 2: rsshub.v1.WeiboUsersReply.list:type_name -> rsshub.v1.WeiboUsersReply.One
	4,  // 3: rsshub.v1.Weibo.Hello:input_type -> rsshub.v1.HelloReq
	0,  // 4: rsshub.v1.Weibo.NewOriginWeibo:input_type -> rsshub.v1.NewOriginWeiboReq
	2,  // 5: rsshub.v1.Weibo.NewAllWeibo:input_type -> rsshub.v1.NewAllWeiboReq
	6,  // 6: rsshub.v1.Weibo.NewAddWeibo:input_type -> rsshub.v1.NewAddWeiboReq
	8,  // 7: rsshub.v1.Weibo.WeiboUsers:input_type -> rsshub.v1.WeiboUsersReq
	5,  // 8: rsshub.v1.Weibo.Hello:output_type -> rsshub.v1.HelloReply
	1,  // 9: rsshub.v1.Weibo.NewOriginWeibo:output_type -> rsshub.v1.NewOriginWeiboReply
	3,  // 10: rsshub.v1.Weibo.NewAllWeibo:output_type -> rsshub.v1.NewAllWeiboReply
	7,  // 11: rsshub.v1.Weibo.NewAddWeibo:output_type -> rsshub.v1.NewAddWeiboReply
	9,  // 12: rsshub.v1.Weibo.WeiboUsers:output_type -> rsshub.v1.WeiboUsersReply
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_weibo_proto_init() }
func file_api_v1_weibo_proto_init() {
	if File_api_v1_weibo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_weibo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewOriginWeiboReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_weibo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewOriginWeiboReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_weibo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewAllWeiboReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_weibo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewAllWeiboReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_weibo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_weibo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_weibo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewAddWeiboReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_weibo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewAddWeiboReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_weibo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeiboUsersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_weibo_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeiboUsersReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_weibo_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeiboUsersReply_One); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_weibo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_weibo_proto_goTypes,
		DependencyIndexes: file_api_v1_weibo_proto_depIdxs,
		MessageInfos:      file_api_v1_weibo_proto_msgTypes,
	}.Build()
	File_api_v1_weibo_proto = out.File
	file_api_v1_weibo_proto_rawDesc = nil
	file_api_v1_weibo_proto_goTypes = nil
	file_api_v1_weibo_proto_depIdxs = nil
}
